from web.func_rumus.dubois import dubois
from web.func_rumus.harris import harris
from web.func_rumus.mifflin import mifflin
from web.func_rumus.perkeni import perkeni
from web.func_rumus.hamil import hamil
from web.func_rumus.menyusui import menyusui
from web.func_rumus.biokimia import biokimia
from web.func_rumus.fisik_klinis import fisik_klinis
from web.func_rumus.makan import makan
from web.func_rumus.mikro import gizimikro